#!/bin/bash
set -e

# Main
main() {
  if [[ "$VERBOSITY" -gt "0" ]]
  then
    echo "REACTION_ROOT='$REACTION_ROOT'"
    cd $REACTION_ROOT
    pwd
    ls
    echo "passing $@"
    echo "to docker-entrypoint.sh"
  fi

  if [ "$#" -ne 0 ]; then
    /assets/docker-entrypoint.sh $@
  else
    /assets/docker-entrypoint.sh sh
  fi
}

main "$@"
