#!/bin/bash
# Runs a command in the reactiondev env and shows you the output
export REACTION_BUILD_NAME=$1
make clean

export BUILD_ARGS=${BUILD_ARGS:-$(cat BUILD_ARGS)}
export REACTION_ROOT=${REACTION_ROOT:-$(cat REACTION_ROOT)}
export TAG=${TAG:-$(cat TAG)}
export PORT=${PORT:-$(cat PORT)}

TMP=$(mktemp -d --suffix=REACTION_TMP)
echo $TMP >> .tmplist

docker run --name reactiondev \
  --cidfile=.reactiondev.cid \
  -e REACTION_ROOT=/home/node/reaction \
  -v $REACTION_ROOT:/home/node/reaction \
  -v $TMP:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(which docker):/bin/docker \
  $TAG \
  docker build $BUILD_ARGS -t $REACTION_BUILD_NAME .

./scripts/push $REACTION_BUILD_NAME
